
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/superstore
    username: tmax
    password: tmax
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: savePersonJob
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      data-locations: classpath:person.sql
      mode: always

server:
  port: 9090
